import { v4 as uuid } from 'uuid'
import type { Opportunity } from './types'

/**
 * 10 seed opportunities across CL, PE, CO in multiple currencies.
 * Reflects realistic AEC pipeline for ASCH SPA consulting.
 */
export function createSeedOpportunities(): Opportunity[] {
  const now = new Date().toISOString()

  return [
    {
      id: uuid(),
      name: 'Planta Desaladora Atacama III',
      client: 'Aguas del Norte',
      country: 'CL',
      sector: 'water',
      clientType: 'owner',
      contractType: 'fee_success',
      stage: 'negotiation',
      valueOriginal: 42_750_000_000,
      valueCurrency: 'CLP',
      valueUSD: 45_000_000,
      aschPercentage: 0.60,
      aschValueUSD: 27_000_000,
      probabilityOfAward: 0.75,
      expectedCloseDate: '2026-04-15',
      expectedStartDate: '2026-07-01',
      deadlineRFP: '2026-03-01',
      teamingPartners: ['WSP', 'Sacyr'],
      tags: ['desalación', 'minería'],
      notes: 'Proyecto emblemático para suministro hídrico minero en Atacama.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2025-11-15', reason: 'Contacto inicial con Aguas del Norte', goNoGo: false },
        { from: 'qualification', to: 'proposal', date: '2026-01-10', reason: 'RFI recibido, perfil de proyecto claro', goNoGo: true },
        { from: 'proposal', to: 'negotiation', date: '2026-02-05', reason: 'Propuesta enviada, en revisión técnica', goNoGo: true },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Central Solar Moquegua 200MW',
      client: 'Enel Green Power Perú',
      country: 'PE',
      sector: 'energy',
      clientType: 'developer',
      contractType: 'fee_success',
      stage: 'proposal',
      valueOriginal: 280_000_000,
      valueCurrency: 'USD',
      valueUSD: 280_000_000,
      aschPercentage: 0.40,
      aschValueUSD: 112_000_000,
      probabilityOfAward: 0.45,
      expectedCloseDate: '2026-06-30',
      expectedStartDate: '2026-10-01',
      teamingPartners: ['Solarpack'],
      tags: ['renovable', 'PMGD'],
      notes: 'Proyecto solar de gran escala en sur de Perú. Adenda Perú aplica.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2025-12-01', reason: 'Referido por contacto ENEL', goNoGo: false },
        { from: 'qualification', to: 'proposal', date: '2026-01-20', reason: 'Due diligence completado', goNoGo: true },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Túnel Minero El Teniente Fase IV',
      client: 'Codelco',
      country: 'CL',
      sector: 'mining',
      clientType: 'government',
      contractType: 'fee_success',
      stage: 'qualification',
      valueOriginal: 85_500_000_000,
      valueCurrency: 'CLP',
      valueUSD: 90_000_000,
      aschPercentage: 0.50,
      aschValueUSD: 45_000_000,
      probabilityOfAward: 0.35,
      expectedCloseDate: '2026-09-30',
      teamingPartners: ['Stantec', 'Hatch'],
      tags: ['underground', 'copper'],
      notes: 'Expansión del complejo minero El Teniente. Alta competencia.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2026-01-05', reason: 'Licitación pública publicada', goNoGo: false },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Puerto Multimodal Barranquilla',
      client: 'Grupo Argos',
      country: 'CO',
      sector: 'infrastructure',
      clientType: 'developer',
      contractType: 'fee_success',
      stage: 'identification',
      valueOriginal: 290_000_000_000,
      valueCurrency: 'COP',
      valueUSD: 70_000_000,
      aschPercentage: 0.35,
      aschValueUSD: 24_500_000,
      probabilityOfAward: 0.20,
      expectedCloseDate: '2026-12-31',
      teamingPartners: [],
      tags: ['puerto', 'logística'],
      notes: 'Nuevo puerto multimodal. Etapa temprana de identificación.',
      stageHistory: [],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Parque Eólico Arauco 150MW',
      client: 'AES Chile',
      country: 'CL',
      sector: 'energy',
      clientType: 'developer',
      contractType: 'fee_success',
      stage: 'proposal',
      valueOriginal: 190_000_000,
      valueCurrency: 'USD',
      valueUSD: 190_000_000,
      aschPercentage: 0.45,
      aschValueUSD: 85_500_000,
      probabilityOfAward: 0.55,
      expectedCloseDate: '2026-05-15',
      expectedStartDate: '2026-08-01',
      deadlineRFP: '2026-04-01',
      teamingPartners: ['Vestas'],
      tags: ['eólica', 'renovable'],
      notes: 'Proyecto eólico en Biobío, ASCH como advisor técnico.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2025-10-20', reason: 'Primera reunión con AES', goNoGo: false },
        { from: 'qualification', to: 'proposal', date: '2025-12-15', reason: 'Aprobado internamente', goNoGo: true },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Planta LNG Regasificación Talcahuano',
      client: 'GNL Chile',
      country: 'CL',
      sector: 'oil_gas',
      clientType: 'owner',
      contractType: 'fee_success',
      stage: 'qualification',
      valueOriginal: 320_000_000,
      valueCurrency: 'USD',
      valueUSD: 320_000_000,
      aschPercentage: 0.30,
      aschValueUSD: 96_000_000,
      probabilityOfAward: 0.30,
      expectedCloseDate: '2026-08-31',
      teamingPartners: ['Bechtel'],
      tags: ['LNG', 'gas'],
      notes: 'Planta de regasificación. Proyecto de alta complejidad técnica.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2026-01-15', reason: 'RFI respondido', goNoGo: false },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Ampliación Cerro Verde - Línea 3',
      client: 'Freeport-McMoRan',
      country: 'PE',
      sector: 'mining',
      clientType: 'owner',
      contractType: 'fee_success',
      stage: 'identification',
      valueOriginal: 450_000_000,
      valueCurrency: 'PEN',
      valueUSD: 120_000_000,
      aschPercentage: 0.25,
      aschValueUSD: 30_000_000,
      probabilityOfAward: 0.15,
      expectedCloseDate: '2027-03-31',
      teamingPartners: [],
      tags: ['copper', 'expansion'],
      notes: 'Fase exploratoria. Ampliación de concentradora.',
      stageHistory: [],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Metro Bogotá — Línea 2',
      client: 'Metro de Bogotá S.A.',
      country: 'CO',
      sector: 'infrastructure',
      clientType: 'government',
      contractType: 'fee_success',
      stage: 'qualification',
      valueOriginal: 2_000_000_000_000,
      valueCurrency: 'COP',
      valueUSD: 490_000_000,
      aschPercentage: 0.10,
      aschValueUSD: 49_000_000,
      probabilityOfAward: 0.25,
      expectedCloseDate: '2027-06-30',
      teamingPartners: ['Arup', 'IDOM'],
      tags: ['metro', 'transport', 'megaproject'],
      notes: 'Megaproyecto de transporte urbano. Alta visibilidad política.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2026-02-01', reason: 'Manifestación de interés enviada', goNoGo: false },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Hospital Regional Iquique',
      client: 'Ministerio de Salud',
      country: 'CL',
      sector: 'infrastructure',
      clientType: 'government',
      contractType: 'fee_success',
      stage: 'won',
      valueOriginal: 28_500_000_000,
      valueCurrency: 'CLP',
      valueUSD: 30_000_000,
      aschPercentage: 1.00,
      aschValueUSD: 30_000_000,
      probabilityOfAward: 1.00,
      expectedCloseDate: '2025-12-15',
      expectedStartDate: '2026-02-01',
      teamingPartners: ['Arcadis'],
      tags: ['salud', 'gobierno'],
      notes: 'Ganada Q4 2025. En ejecución.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2025-06-01', reason: 'Licitación MOP', goNoGo: false },
        { from: 'qualification', to: 'proposal', date: '2025-08-15', reason: 'Pre-calificación aprobada', goNoGo: true },
        { from: 'proposal', to: 'negotiation', date: '2025-10-20', reason: 'Oferta en lista corta', goNoGo: true },
        { from: 'negotiation', to: 'won', date: '2025-12-15', reason: 'Adjudicada', goNoGo: true },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      name: 'Proyecto Hidroeléctrico Alto Maipo II',
      client: 'AES Gener',
      country: 'CL',
      sector: 'energy',
      clientType: 'developer',
      contractType: 'mixed',
      stage: 'lost',
      valueOriginal: 150_000_000,
      valueCurrency: 'USD',
      valueUSD: 150_000_000,
      aschPercentage: 0.50,
      aschValueUSD: 75_000_000,
      probabilityOfAward: 0,
      expectedCloseDate: '2025-11-30',
      teamingPartners: ['SNC-Lavalin'],
      tags: ['hydro'],
      notes: 'Perdida en Q4 2025. Competidor ofreció condiciones más agresivas.',
      stageHistory: [
        { from: 'identification', to: 'qualification', date: '2025-05-01', reason: 'Reunión exploratoria', goNoGo: false },
        { from: 'qualification', to: 'proposal', date: '2025-07-10', reason: 'RFP recibido', goNoGo: true },
        { from: 'proposal', to: 'negotiation', date: '2025-09-20', reason: 'Short-listed', goNoGo: true },
        { from: 'negotiation', to: 'lost', date: '2025-11-30', reason: 'Adjudicada a competidor', goNoGo: false },
      ],
      invoices: [],
      contactIds: [],
      createdAt: now,
      updatedAt: now,
    },
  ]
}
